data:
  train_batch_size: 256
  valid_batch_size: 256
  train_micro_batch_size_per_gpu: 32
  valid_micro_batch_size_per_gpu: 32
  train_data: ./data/NuminaMath-CoT-Small-Hard-200k/preprocessed/train.nano
  valid_data: ./data/NuminaMath-CoT-Small-Hard-200k/preprocessed/valid.nano
  num_workers: 8

model:
  model_name_or_path: Qwen/Qwen3-0.6B-base
  tokenizer_name_or_path: Qwen/Qwen3-0.6B
  tensor_parallel_size: 2
  pipeline_parallel_size: 2
  data_parallel_size: 2
  zero_stage: 1
  host: 127.0.0.1
  port: 23333
  backend: nccl
  seed: 42
  gradient_checkpointing_enable: true

optim:
  lr: 1e-5
  min_lr: 1e-6
  lr_warmup_steps_ratio: 0.1
  lr_scheduler: cosine
  beta1: 0.9
  beta2: 0.95
  clip_grad: 1.0
  weight_decay: 1e-3

training:
  default_local_dir: ./checkpoints
  project_name: math
  experiment_name: sft
  total_epochs: 3
  wandb: true
  seed: 42
  save_freq: 500
  test_freq: 500