data:
  train_batch_size: 256
  valid_batch_size: 256
  ppo_mini_batch_size_per_gpu: 32
  ppo_micro_batch_size_per_gpu: 4
  ppo_epochs: 1
  train_data: ./data/DeepMath-84k/preprocessed/train.nano
  valid_data: ./data/MATH-500/preprocessed/valid.nano
  num_workers: 8

actor:
  model_name_or_path: "./checkpoints/math/sft/step_2000/merged"
  tokenizer_name_or_path: "./checkpoints/math/sft/step_2000/merged"
  tensor_parallel_size: 2
  pipeline_parallel_size: 2
  data_parallel_size: 1
  zero_stage: 0
  host: 127.0.0.1
  port: 23333
  backend: nccl
  seed: 42
  gradient_checkpointing_enable: true

rollout:
  model_name_or_path: "./checkpoints/math/sft/step_2000/merged"
  max_num_batched_tokens: 65536
  max_num_seqs: 1024
  max_model_len: 4096
  max_prompt_len: 1024
  max_response_len: 3072
  gpu_memory_utilization: 0.9
  kvcache_block_size: 256
  tensor_parallel_size: 2
  data_parallel_size: 2
  enforce_eager: false
  temperature: 0.7
  # The 0.6B model is often under-confident, the top-1 probability is very low.
  # so we use temperature=0.7 to keep generations stable while still allowing some exploration.

reward:
  name: compute_score
  path: nanorlhf.nanoverl.reward.custom_reward_fn

optim:
  lr: 1e-6
  min_lr: 0
  lr_warmup_steps_ratio: 0.1
  lr_scheduler: cosine
  beta1: 0.9
  beta2: 0.95
  clip_grad: 1.0
  weight_decay: 1e-3

algorithm:
  gamma: 1.0
  lam: 1.0
  use_kl_in_reward: false
  kl_loss_coef: 0.01
  vf_loss_coef: 0.1
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_value: 0.2

training:
  default_local_dir: ./checkpoints
  project_name: math
  experiment_name: rl
  total_epochs: 3
  wandb: true
  seed: 42
  save_freq: 50
  test_freq: 50
